name: aws-build-and-push

on:
#   push:
#     branches:
#       - master
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Lambda Function zip file
        run: zip inapp_media_mediaconvert.zip inapp_media_mediaconvert.js
        working-directory: src/functions/aws/

      - name: Print src aws directory
        run: ls src/functions/aws/

      - name: Copy Lambda Function zip file to s3 bucket
        run: |
          aws s3 cp src/functions/aws/inapp_media_mediaconvert.zip s3://inappmedia-lambda-code-s3-bucket/LambdaSource/functions/dashboard/mediaconvert/inapp_media_mediaconvert.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1" 