name: Maven Build and Deploy to S3

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Get current date
        if: github.ref == 'refs/heads/master'
        id: get-date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Create Asset
        if: github.ref == 'refs/heads/master'
        run: zip account-fix-demo.zip target/keycloak-account-ext.jar
      
      - name: Create Draft Release
        if: github.ref == 'refs/heads/master'
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: v${{ steps.get-date.outputs.date }}.${{ github.run_number }}
          release_name: v${{ steps.get-date.outputs.date }}.${{ github.run_number }}
          draft: true
          prerelease: false

      - name: Upload assets to the release
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: account-fix-demo.zip
          asset_name: account-fix-demo.zip
          asset_content_type: application/zip

      - name: Delete older drafted releases
        uses: sgpublic/delete-release-action@v1.1
        if: github.ref == 'refs/heads/master'
        with:
          draft-drop: true
          draft-drop-count: 0
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Publish Release
        if: github.ref == 'refs/heads/master'
        run: echo "You can publish release from here - ${{ steps.create_release.outputs.html_url }}"