name: Test-Github

run-name: Testing

on:
    workflow_dispatch:
    
jobs:
    Clear-Sessions:
        runs-on: "ubuntu-latest"
        steps:
        - name: Checkout Cloudflare repo
          uses: actions/checkout@v3
        
        - name: Clear Sessions for 10 minutes
          id: clear-sessions
          run: |
            set -euxo pipefail
            python3 ./scripts/clear_sessions.py --client_id ${{ secrets.CLIENT_ID }} --client_secret_key ${{ secrets.CLIENT_SECRET }}

    