name: aws/Shutdown-Instance

on: 
    pull_request:
        branches:
        - 'main'
        types: [opened, synchronize, reopened]
    workflow_dispatch:

jobs:
  execute-shutdown-instance-on-aws:
    runs-on: sk1
    steps:
      - name: Checkout cloudflare repo
        uses: actions/checkout@v3

      - name: Get Instances
        run: |
            set -euxo pipefail
            INSTANCE_IDS=$(aws ec2 describe-instances \
            --region ap-northeast-2 \
            --filters "Name=tag:StackName,Values=testing-1" \
            --query 'Reservations[*].Instances[*].InstanceId' \
            --output text | tr '\n' ' ' | xargs)
            echo $INSTANCE_IDS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}