name: Site build

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Print Full GitHub Event
      run: |
        echo "Event Payload:"
        echo '${{ toJson(github.event) }}'