name: Test-Github

run-name: Testing

on:
  workflow_dispatch:
    inputs:
      StackPrefix:
        type: string
        description: Stack Prefix of region
        required: true

  push:
      branches:
        "*"
    

jobs:
    Test-Silence:
        runs-on: "ubuntu-latest"
        steps:
        - name: Checkout Cloudflare repo
          uses: actions/checkout@v3
        
        - name: Silence for 10 minutes
          id: silence-for-10-mins
          continue-on-error: true
          run: |
            set -euxo pipefail
            pwd
            ls
            python3 ./scripts/silence_last9_lp_alerts.py --region ${{ inputs.StackPrefix }} --access_token ${{ secrets.REFRESH_TOKEN }}

        - name: Echo test
          run: |
            echo "I am running"
      
    New-Job:
      runs-on: "ubuntu-latest"
      needs: 
      steps:
        - name: Echo test
          run: |
            echo "I am a New job"
    