name: Site build

on:
  workflow_dispatch:
    inputs:
      client:
        description: "Client name"
        required: false
        type: string
      client_url:
        description: "Client URL"
        required: false
        type: string
      description:
        description: "Alert description"
        required: false
        type: string
  repository_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Print Full GitHub Event
      run: |
        echo "Event Payload:"
        echo '${{ toJson(github.event) }}'
        echo "Client: ${{ github.event.inputs.client }}"
        echo "Client URL: ${{ github.event.inputs.client_url }}"
        echo "Description: ${{ github.event.inputs.description }}"
